/*	
  Script: createdb.sql
 By Sarah Deters	
  Last Modified: 1-May-2018
	
  Purpose: Creates the database tables, constraints, and other necessary commands
*/
CREATE TABLE HEAD (Code NUMBER(4,0) PRIMARY KEY, Name VARCHAR2(20) UNIQUE NOT NULL, HType CHAR(1), HDate DATE, OpBal NUMBER(6,2), CONSTRAINT HEAD_HType_cc CHECK (HType IN ('A','E','L','R')));
CREATE TABLE SUBHEAD (HCode NUMBER(4,0), SubCode NUMBER(4,0), Name VARCHAR2(20), SDate DATE, OpBal NUMBER(6,2), CONSTRAINT pk_SUBHEAD PRIMARY KEY (HCode, SubCode), CONSTRAINT SUBHEAD_HCode_fk FOREIGN KEY (HCode) REFERENCES HEAD(Code));
CREATE TABLE CRCARD (CType CHAR(1), CCNum VARCHAR2(16), ExpDate DATE, CRLimit NUMBER(6,2), CONSTRAINT pk_CRCARD PRIMARY KEY (CType, CCNum), CONSTRAINT CRCARD_CType_cc CHECK (CType IN ('V','M','D')));
CREATE TABLE STORE (Name VARCHAR2(20) UNIQUE NOT NULL, Code CHAR(2) PRIMARY KEY);
CREATE SEQUENCE ExpNumInc
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
CREATE TABLE EXPMAST (ExpNum NUMBER(10,0) PRIMARY KEY, EDate DATE, CashAmt NUMBER(6,2), StoreCode CHAR(2), CONSTRAINT EXPMAST_StoreCode_fk FOREIGN KEY (StoreCode) REFERENCES STORE(Code));
CREATE TABLE EXPDET (ExpNum NUMBER(10,0), LineNum NUMBER(5,0) UNIQUE,Descrip VARCHAR2(20), Amt NUMBER(6,2),HCode NUMBER(4,0), SubCode NUMBER(4,0),CONSTRAINT pk_EXPDET PRIMARY KEY (ExpNum, LineNum),CONSTRAINT EXPDET_ExpNum_fk FOREIGN KEY (ExpNum) REFERENCES EXPMAST(ExpNum) ON DELETE CASCADE,CONSTRAINT EXPDET_HCode_fk FOREIGN KEY (HCode, SubCode) REFERENCES SUBHEAD(HCode, SubCode) ON DELETE CASCADE);
CREATE TABLE ExpByCC (ExpNum NUMERIC(10,0), CType CHAR(1), CCNum VARCHAR2(16), Amt NUMBER(6,2),CONSTRAINT pk_ExpByCC PRIMARY KEY (ExpNum, CType, CCNum),CONSTRAINT ExpByCC_ExpNum_fk FOREIGN KEY (ExpNum) REFERENCES EXPMAST(ExpNum) ON DELETE CASCADE,CONSTRAINT ExpByCC_CType_fk FOREIGN KEY (CType, CCNum) REFERENCES CRCARD(CType, CCNum) ON DELETE CASCADE);