/*	
  Script: deldb.sql
 By Sarah Deters	
  Last Modified: 1-May-2018
	
  Purpose: Deletes the whole database.


*/
DROP TABLE ExpByCC CASCADE CONSTRAINTS PURGE;
DROP TABLE EXPDET CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE ExpNumInc;
DROP TABLE EXPMAST CASCADE CONSTRAINTS PURGE;
DROP TABLE STORE CASCADE CONSTRAINTS PURGE;
DROP TABLE CRCARD CASCADE CONSTRAINTS PURGE;
DROP TABLE SUBHEAD CASCADE CONSTRAINTS PURGE;
DROP TABLE HEAD CASCADE CONSTRAINTS PURGE;






